### PR TITLE
Call span.end() in the happy path in withSpan

### LINKED ISSUE #30: withSpan() doesn’t work as documented
The documentation comments clearly state:

> DO NOT `end()` the passed in span manually. It will be ended automatically when the `function` returns.

However, there is no `end()` on the happy path, only if an error occurs.

Of course I could make a PR, but when I encountered this I convinced myself that such an obvious omission _might_ be intentional. :-)

### PR DESCRIPTION
**Pull request by JensAyton**
Updates behaviour of `withSpan` to match documentation.

I would consider also making the `context` form of `withSpan` (which is untested) call into the `baggage` variant.

Fixes #30

### CODE REVIEW

File: Tests/TracingTests/TracerTests.swift [hunk 1]
```diff
@@ -63,11 +63,15 @@ final class TracerTests: XCTestCase {
...
 
+        var spanEnded = false
+        tracer.onEndSpan = { _ in spanEnded = true }
+
         let value = tracer.withSpan("hello", baggage: .topLevel) { _ in
             "yes"
         }
 
         XCTAssertEqual(value, "yes")
+        XCTAssertEqual(spanEnded, true)
```
Comment (slashmo) [inline Tests/TracingTests/TracerTests.swift:74]:
```suggestion
        XCTAssert(spanEnded)
```

File: Tests/TracingTests/TracerTests.swift [hunk 2]
```diff
@@ -77,11 +81,15 @@ final class TracerTests: XCTestCase {
...
 
+        var spanEnded = false
+        tracer.onEndSpan = { _ in spanEnded = true }
+
         do {
             _ = try tracer.withSpan("hello", baggage: .topLevel) { _ in
                 throw ExampleSpanError()
             }
         } catch {
+            XCTAssertEqual(spanEnded, true)
```
Comment (slashmo) [inline Tests/TracingTests/TracerTests.swift:92]:
```suggestion
            XCTAssert(spanEnded)
```

**Review by slashmo — APPROVED** [review]
Thanks for taking this on, @JensAyton! 👍 LGTM, just some minor nitpicks to clean up the assertions.

**Comment by slashmo** [comment]
> I would consider also making the context form of withSpan (which is untested) call into the baggage variant.
> @JensAyton

Sounds good to me. Would you mind adding this as well?

**Comment by tomerd** [comment]
@swift-server-bot add to whitelist

File: Tests/TracingTests/TracerTests.swift (hunk 1 above)
Comment (tomerd) [reply Tests/TracingTests/TracerTests.swift:74]: also `XCTAssertTrue` if you want to be more explicit

Comment (ktoso) [reply Tests/TracingTests/TracerTests.swift:74]:
```suggestion
        XCTAssertTrue(spanEnded)
```

File: Tests/TracingTests/TracerTests.swift (hunk 2 above)
Comment (ktoso) [reply Tests/TracingTests/TracerTests.swift:92]:
```suggestion
            XCTAssertTrue(spanEnded, true)
```

**Comment by ktoso** [comment]
Let me merge this and let's do 

> I would consider also making the context form of withSpan (which is untested) call into the baggage variant.


in a follow up please @JensAyton ?

Thanks a lot!
